version: '3.8'

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: verses-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - pg_data:/bitnami/postgresql
    networks:
      - verses-network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: verses-backend
    restart: always
    environment:
      - NODE_ENV=production
      
      - DATABASE_URL=${DATABASE_URL}
      - BROKER_URL=${BROKER_URL}
      - DB_HOST=verses-db
      - DB_PORT=5432
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - ABIBLIA_DIGITAL_URL=${ABIBLIA_DIGITAL_URL}
      - ABIBLIA_DIGITAL_TOKEN=${ABIBLIA_DIGITAL_TOKEN}
      - OTEL_TRACES_EXPORTER=${OTEL_TRACES_EXPORTER}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_NODE_ENABLED_INSTRUMENTATIONS=${OTEL_NODE_ENABLED_INSTRUMENTATIONS}
    networks:
      - verses-network
    
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pg_data:

networks:
  verses-network:
    external: true